### ISSUE TITLE
C14N choice criteria

### ISSUE THREAD

**Issue by philarcher** [w3c/rdf-canon#10]
In the [meeting on 2022-10-12](https://www.w3.org/2022/10/12-rch-minutes.html), we discussed criteria that can be used to make a choice between alternative choices in specific steps in the c14n algorithm. The initial list of suggestions is below. We need to formalize this and, IMO, include it in the [explainer doc](https://www.w3.org/2022/07/rch-wg-charter/explainer.html).

- ease of implementation
- existing incubation / use in the marketplace
- time / resource complexity in solving common datasets
- time / resource complexity in solving complex (or poison?) datasets
-  Existence of formal proofs for the algorithms
-  Demonstration of review of formal proofs for the algorithms
- reusing existing primitives that are available on various platforms
- cover real life examples

**Comment by afs** [comment]
Other criteria mentioned:

* Addresses dataset canonicalization, not just graphs
* Bounded datasets (the whole dataset is available, not a stream of quads)
* The algorithm(s) covers all datasets, not a subset (the execution of the algorithm may be impractical)
* Prefer that it covers RDF-star (subject to that working group's direction)
* Covers generalized RDF (bnodes and literals in any position)

**Comment by dlongley** [comment]
> Covers generalized RDF (bnodes and literals in any position)

Do we have a use case for needing to canonize generalized RDF? Or is this a "nice to have" ... and "how nice" would it be? I would expect having to support it would introduce additional complexity and more "poison graph" cases due to bnodes appearing in the predicate position.

**Comment by iherman** [comment]
> > Covers generalized RDF (bnodes and literals in any position)
> 
> Do we have a use case for needing to canonize generalized RDF? Or is this a "nice to have" ... and "how nice" would it be? I would expect having to support it would introduce additional complexity and more "poison graph" cases due to bnodes appearing in the predicate position.

As far as I know, there aren't much "generalized" RDF graphs out there. Certainly the "big" datasets, like schema.org or dbpedia are standard RDF graphs (and, as far as I could see, so are VC graphs).

In my view these are nice to have, but if they complicate the algorithm in any way, then we should drop it.

**Comment by gkellogg** [comment]
> > Covers generalized RDF (bnodes and literals in any position)
> 
> Do we have a use case for needing to canonize generalized RDF? Or is this a "nice to have" ... and "how nice" would it be? I would expect having to support it would introduce additional complexity and more "poison graph" cases due to bnodes appearing in the predicate position.

My guess is that the complexity of adding Generalized RDF is about the same as RDF-star. An algorithm that doesn't make too many assumptions about the number or locations of the blank nodes in a statement would be the most general.

IMO, if the RDF-star WG proceeds more or less in the existing path that this group can't leave it as a "nice to have" feature.

**Comment by iherman** [comment]
> IMO, if the RDF-star WG proceeds more or less in the existing path that this group can't leave it as a "nice to have" feature

👍 to that. _If_ there is a choice to make between RDF-star and generalized RDF than, in my view, RDF-star should be chosen. In other words, the possibility to go towards RDF-star is a must.

**Comment by gkellogg** [comment]
> > > Covers generalized RDF (bnodes and literals in any position)
> > 
> > 
> > Do we have a use case for needing to canonize generalized RDF? Or is this a "nice to have" ... and "how nice" would it be? I would expect having to support it would introduce additional complexity and more "poison graph" cases due to bnodes appearing in the predicate position.
> 
> As far as I know, there aren't much "generalized" RDF graphs out there. Certainly the "big" datasets, like schema.org or dbpedia are standard RDF graphs (and, as far as I could see, so are VC graphs).
> 
> In my view these are nice to have, but if they complicate the algorithm in any way, then we should drop it.

The Activity Streams context (located at https://www.w3.org/ns/activitystreams via content-negotiation) uses `"@vocab": "_:"`, meaning that any graph derived from an activity stream could potentially have blank node predicates. We discovered this in JSON-LD 1.1 when we were considering deprecating the use of blank nodes in the property position. In stead, we marked them as "obsolete", to not encourage any further use.

Notation3, which some might interpret as RDF, allows any resource type in any position (including formulae), although there aren't generally use cases for anything other than literals as subjects.

**Comment by iherman** [comment]
As, at the end of the day, the two algorithms we will have to choose from are blabel and URDNA, we can shorten this list right away, just to ease our own work. For example:

> ease of implementation

None of the two are easy to implement :-) but as the comparison in, say, #6 shows, their structure is fairly similar and I do not think the implementation effort is fundamentally different. (Ok, I acknowledge this may be a subjective reaction.)

>Existence of formal proofs for the algorithms
> Demonstration of review of formal proofs for the algorithms

Though by different processes I believe these holds for both cases (blabel went through a rigorous academic review process several times, because the algorithm was published in a conference _and_ in a very highly praised academic journal; URDNA had a similarly rigorous review that was published at the time of chartering.)

> Addresses dataset canonicalization, not just graphs

URDNA is prepared for datasets out of the box. Although blabel was formulated for graphs only, its extension to dataset is trivial (see https://github.com/iherman/canonical_rdf/blob/master/Readme.md)

> Bounded datasets (the whole dataset is available, not a stream of quads)
> The algorithm(s) covers all datasets, not a subset (the execution of the algorithm may be impractical)

I believe this is simply true for both cases out of the box...

**Comment by dlongley** [comment]
@gkellogg,

> The Activity Streams context (located at https://www.w3.org/ns/activitystreams via content-negotiation) uses "@vocab": "_:", meaning that any graph derived from an activity stream could potentially have blank node predicates. 

I think that's probably a mistake, though. I'd rather us not encourage people to continue to create data that gets dropped or needs special processing -- it makes it less interoperable and harder to use securely.

Additionally, even in the case that bnodes show up in the predicate position in JSON-LD data, this data is dropped when converting to RDF unless a special flag is set. I know that we're pushing for errors to be raised in the Data Integrity work if any data is dropped when converting to RDF (and we're using standard RDF, not generalized RDF). So any data that had bnodes in the predicate position would generate errors (in DI) prior to being canonized.

**Comment by dlongley** [comment]
@gkellogg,

> My guess is that the complexity of adding Generalized RDF is about the same as RDF-star. An algorithm that doesn't make too many assumptions about the number or locations of the blank nodes in a statement would be the most general.

Hmm, I'm not sure that the complexity would be similar. Perhaps it depends what kind of "complexity" we're talking about (implementation complexity or time / resource complexity).

During the most complex parts of the bnode labeling algorithm (by any measure), whenever some order on bnodes can be uniformly imposed, it eliminates the need to enumerate additional possible orderings, at great savings. If the order of bnodes in a particular statement are always in the same order -- then you can potentially assign temporary labels in that same order. Adding more bnodes to the same statement shouldn't change this (as long as they are well ordered). But if the links between statements are themselves now unordered and need their own labels, the number of steps / difficulty in labeling could be significantly higher. There might be a need for another overall layer of iterating / enumeration.

I'm sure an algorithm could be constructed to treat all components of a statement the same, but I can't say with confidence that it would come cheaply.

**Comment by TallTed** [comment]
@dlongley — Please edit your https://github.com/w3c/rch-rdc/issues/10#issuecomment-1277894478 and add code fences around `"@vocab": "_:"` (or at least around `@vocab` therein) in the quote block...

**Comment by afs** [comment]
Generalized RDF is issue #7.
It's mentioned in the charter.
It arises in rules situations naturally.
nary-relations have to take active steps (more triples, less clear) to not use blank nodes in the predicate position when they would prefer to,
JSON-LD extended RDF datasets with blank nodes in the graph name position.

> some order on bnodes can be uniformly imposed 

A quad is an ordered tuples so position in quad is one factor.

We already need defences against graphs that are expensive to canonicalize. We can not rely solely on on being able to enumerate once and for all what the conditions on the graph might be to cause it to be expensive. One application domain idea of expensive if not necessarily the same as another domain.

We need to defend based on the effect, not by known causes. Some graphs will be computationally too expensive to process. It's not going to be hard to generate them - put in some cliches.

**Comment by gkellogg** [comment]
> @gkellogg,
> 
> > The Activity Streams context (located at https://www.w3.org/ns/activitystreams via content-negotiation) uses `"@vocab": "_:"`, meaning that any graph derived from an activity stream could potentially have blank node predicates.
> 
> I think that's probably a mistake, though. I'd rather us not encourage people to continue to create data that gets dropped or needs special processing -- it makes it less interoperable and harder to use securely.

While I agree that it's a bad idea, I don't think that it was done unintentionally. Recall that in the JSON-LD 1.0 time frame we were looking to simplify the ability for people to use JSON-LD without a well-defined vocabulary to lower the barrier to entry. In 1.1 we allowed `@vocab` to be relative to the document location, allowing for patterns similar to those used in many Turtle examples, but we hadn't considered it at the time. IIRC, we had examples in the wild that used the blank-node property pattern. To this day, we have a test [expand/0075](https://w3c.github.io/json-ld-api/tests/expand-manifest.html#t0075) that uses this pattern.

```json
{
  "@context": {
    "@vocab": "_:"
  },
  "@id": "ex:node1",
  "b1": "blank node property 1",
  "b2": "blank node property 1"
}
```

Certainly, if Activity Streams goes for revision, we should encourage a move away from using `"@vocab": "_:"`, as it is not useful, but until then, and for sometime after, it is out in the world.

> Additionally, even in the case that bnodes show up in the predicate position in JSON-LD data, this data is dropped when converting to RDF unless a special flag is set. I know that we're pushing for errors to be raised in the Data Integrity work if any data is dropped when converting to RDF (and we're using standard RDF, not generalized RDF). So any data that had bnodes in the predicate position would generate errors (in DI) prior to being canonized.

Yes, that flag is [produceGeneralizedRdf](https://www.w3.org/TR/json-ld11-api/#dom-jsonldoptions-producegeneralizedrdf), which solely relates to blank node properties. If our algorithm is expected to deal with Generalized RDF, it may need a similar flag to consider such data valid, and potentially enable some processing paths.

Additionally, while the practice has been that a named graph named with a blank node which is also used as a subject or object to relate the statement to the named graph, this is not a normative relationship in RDF 1.1, and potentially, the blank node labels could be disconnected. I think this would be a bad idea, as this is used by Verifiable Claims, and specifically supported in JSON-LD, but we may need a statement that says that for the purposes of the canonicalization algorithm, they are intended to remain syntactically connected (if not semantically). From RDF 1.1 Concepts:

> Despite the use of the word “name” in “[named graph](https://www.w3.org/TR/rdf11-concepts/#dfn-named-graph)”, the [graph name](https://www.w3.org/TR/rdf11-concepts/#dfn-graph-name) is not required to [denote](https://www.w3.org/TR/rdf11-concepts/#dfn-denote) the graph. It is merely syntactically paired with the graph

**Comment by iherman** [comment]
>> The Activity Streams context (located at https://www.w3.org/ns/activitystreams via content-negotiation) uses "@vocab": "_:", meaning that any graph derived from an activity stream could potentially have blank node predicates.

Ouch. This should have been caught when reviewing the spec as being ill-advised regardless of c14n...

**Comment by pchampin** [comment]
Mentioned during today's call: https://www.w3.org/2022/11/23-rch-minutes.html#t05

**Comment by aidhog** [comment]
If a number of different representations beyond RDF graphs/datasets need to be handled, a simple solution would be to just define one algorithm and then use "reifications" of other representations to encode them as RDF graphs/datasets in order to get the blank node mapping. This would add some computational cost versus a dedicated algorithm for each representation, but not much I suspect. On the other hand, it would simplify the spec considerably.

If necessary to distinguish the reification from that which is reified, the mapping can be written back into a serialisation of the original structure (assuming blank node labels are allowed in some syntax of the original structure, or at least the blank nodes can be ordered). 

Another option would be to define an algorithm for a set of arbitrary tuples of RDF terms (which would still not cover RDF-star, however, without reification, unless RDF tuples were also allowed as RDF terms).

There's nothing technically difficult here, but the question is how to do something modular so that there aren't _n_ variations of almost the same algorithm for RDF graphs, RDF datasets, generalised RDF graphs, generalised RDF datasets, RDF-star graphs, RDF-star datasets, generalised RDF-star, ..., etc. (which would result in a repetitive spec, duplicated implementation effort, repetition in proving properties about those algorithms, poor extensibility, etc.). My suggestion would be to define one algorithm for one such structure, and use that as a black box for all the other structures.

**Comment by aidhog** [comment]
The criteria look great to me.

> time / resource complexity in solving common datasets
time / resource complexity in solving complex (or poison?) datasets

Regarding common datasets, I guess there are not that many RDF datasets in the wild. There are however millions upon millions of RDF graphs available on the Web from hundreds/thousands of websites. Perhaps other stakeholders could suggest datasets for use-cases.

Regarding complex datasets, there are known hard cases for graph isomorphism that could be used, so those could be converted into RDF graphs/datasets ([as an example](https://arxiv.org/abs/1705.03686)). Comparison could also be run on the same graphs as used by [Mirabolic Consulting](https://lists.w3.org/Archives/Public/public-credentials/2021Apr/att-0032/Mirabolic_Graph_Iso_Report_2020_10_19.pdf).

> Existence of formal proofs for the algorithms
Demonstration of review of formal proofs for the algorithms

This points to the more general point of correctness, or rather the issue is: how confident do we need to be of correctness in order for the standard to proceed with an algorithm? (In other words, I do not see the issue of correctness as boolean, but rather as continuous, in terms of confidence of correctness.)

Both algorithms have proofs, and these proofs have been formally reviewed, but it is difficult to quantify how, in both cases, this translates into confidence of correctness (other than improving confidence). Proving things is hard. Verifying proofs is even harder. In the case of peer review, it is common for reviewers to glance over proofs (unless the result is somehow surprising). In the case of the [(thorough) review by Mirabolic Consulting](https://lists.w3.org/Archives/Public/public-credentials/2021Apr/att-0032/Mirabolic_Graph_Iso_Report_2020_10_19.pdf), they mention that they found no substantive errors in the proof, but this is not equivalent to saying that the proofs are correct; in the subsection on "Correctness by Design", they give a very insightful discussion on the problem of proving correctness for such an algorithm and verifying such a result.

On the plus side, both algorithms have been empirically demonstrated to work fine for counter-examples from the graph isomorphism literature.

So we can have some confidence of correctness in both cases, but I would not bet my house on the correctness of either algorithm. If my house were on the line, I would certainly look to follow up further on this issue before proceeding.

---------------------------------

As a rough sketch, in terms of proving correctness, one can show that:

* The output of the algorithm does not depend on non-deterministic information that varies under isomorphism, such as the labels given to blank nodes in the input, the ordering of triples in the input graph, the ordering of graphs in an input dataset, etc. (In this case, all such information is a result of syntax.) So either the algorithm "discards" such information, or if it uses it, it does so in a manner that is provably insensitive to such information (either by applying an operation that is insensitive to the information; e.g., applying hashing that gives the same result no matter the particular order of triples or graphs; or by trying all non-deterministic possibilities and choosing one, e.g., trying all possible orders of triples or graphs and using some deterministic criteria to choose the output for one of those orders).
* The output of the algorithm is isomorphic with the input.
* The algorithm is deterministic (it's a function) and it terminates.

The first point is the hard part. An algorithm must process the triples in some order, it must use some "label" to distinguish different blank nodes in the input, etc., so it cannot avoid the information it is not supposed to have. The goal then is to show that the output of the algorithm is invariant to how that information happens to be presented in the input.

**Comment by TallTed** [comment]
It seems to me that test datasets could be chosen from the nodes of the [Linked Open Data Cloud](https://lod-cloud.net/). There are smaller and larger nodes, which might be comprised of one or many graphs. Interconnections could allow datasets to be constructed by loading multiple nodes, much as been done on the [LOD Cloud Cache](https://lod.openlinksw.com/fct/).

**Comment by philarcher** [comment]
The group's dynamic has focused on the URDNA2015 work. We have spent several calls and email threads considering different algorithms and have arrived at the current state. There has been no push to change the basic algorithm from that since this issue was last commented upon. Therefore we propose that the issue be closed.
