### ISSUE TITLE
explanation of NP-intermediate

### ISSUE THREAD

**Issue by gkellogg** [w3c/rdf-canon#122]
From https://github.com/w3c/rdf-canon/issues/111:

>> it is believed to be an NP-Intermediate problem, that is, neither known to be solvable in polynomial time nor NP-complete

> Whether something is an NP-intermediate problem does not depend on what is known about it. The 'believed' already covers for the fact that its status is not known.

> As a scholar, I would also find it natural if there somewhere in the document was explained how (undirected) Graph Isomorphism reduces to RDF Graph C14n. Easiest reduction I can think of would be that each vertex and each edge has a blank node, and the triples all encode the incidence relation (i.e., all predicates are the same, having vertex node as subject and edge node as object). If however you say that as a matter of style going into such detail is not appropriate, then I certainly would believe that.

**Comment by dlongley** [comment]
I wonder if this is just a misreading of the sentence. The second clause in the sentence is explaining more about what NP-intermediate means and why it is important to the reader, not trying to (and failing) to say more about the particular problem or what makes it NP-intermediate.

In other words, the text means this:

> [The graph-isomorphism problem] is "believed to be NP-Intermediate" ... and "an NP-Intermediate problem is one that is not known to be solvable in polynomial time nor NP-complete".

Not this:

> [The graph-isomorphism problem] is "believed to be NP-Intermediate" ... and "[the graph-isomorphism problem] is not known to be solvable in polynomial time nor NP-complete".

It could be, that as an academic, the person who raised the issue was not expecting "NP-Intermediate" to need any explanation, so they took the latter clause to have some other meaning than what was intended. Or maybe this is related to the reader potentially being a non-native English speaker? Or... I'm maybe misreading what they meant ... or something else entirely! :)

We could make the text say:

> it is believed to be an NP-Intermediate problem. An NP-Intermediate problem is one that is neither known to be solvable in polynomial time nor NP-complete.

But that's a bit more clunky. We could also just close with the expectation that this was a one-off misreading.

**Comment by TallTed** [comment]
How about —
> It is believed to be an NP-Intermediate problem. An NP-Intermediate problem is one that is neither known to be solvable in polynomial time nor NP-complete. (See https://en.wikipedia.org/wiki/NP-intermediate.)

If there's a preferred discussion page somewhere not-Wikipedia, that'd be fine, too.

(This comment seems rather esoteric and of questionable importance in the document. Is it really important to the reader? Or is it more important to the authors, i.e., us?)

**Comment by gkellogg** [comment]
We might reference Aiden's paper where he note that the graph homomorphism problem is NP-complete, although states that graph isomorphism is not (GI-complete). I think there is more in his paper that we can reference from the spec.

**Comment by philarcher** [comment]
Discussed 2023-06-21. Suggested that help would be appreciated with this. @dlongley Can you please?

**Comment by dlongley** [comment]
I'm inclined to go along with @TallTed's comments:

> (This comment seems rather esoteric and of questionable importance in the document. Is it really important to the reader? Or is it more important to the authors, i.e., us?)

I don't think it's important enough to put any more effort into clarifying it -- or dealing with any other possible misunderstandings around it. It doesn't affect the spec -- so we should just remove the sentence.

I've raised #133 to address this issue.

**Comment by gkellogg** [comment]
Closed via #133.
